# Generated by Django 5.1.4 on 2025-01-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('house_type', models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Three Bedroom', 'Three Bedroom')], max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
