# Generated by Django 5.1.4 on 2025-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='payment',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='overdue_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
