# Generated by Django 5.1.4 on 2025-01-16 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_tenant_date_joined_payment_overdue_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
