# Generated by Django 5.1.4 on 2025-01-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_tenant_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
