# Generated by Django 5.1.4 on 2025-02-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_tenant_credit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='overdue_amount',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='overdue_balance',
        ),
    ]
